# Generated by Django 4.1.5 on 2023-01-19 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servuser',
            new_name='Servusers',
        ),
        migrations.RenameModel(
            old_name='Spec',
            new_name='Specs',
        ),
    ]
