# Generated by Django 4.0.3 on 2023-01-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servusers', '0002_rename_servuser_servusers_rename_spec_specs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servusers',
            old_name='spec',
            new_name='spec_id',
        ),
        migrations.RenameField(
            model_name='specs',
            old_name='spec_type',
            new_name='spec',
        ),
    ]
