# Generated by Django 3.1 on 2023-01-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servusers', '0003_rename_spec_servusers_spec_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servusers',
            old_name='spec_id',
            new_name='spec',
        ),
        migrations.RenameField(
            model_name='specs',
            old_name='spec',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='servusers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
